# Generated by Django 3.2 on 2025-06-19 21:40

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('moderator', 'Модератор'), ('admin', 'Админ')], default='user', max_length=9, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[users.validators.validate_name]),
        ),
        migrations.DeleteModel(
            name='EmailConfirmation',
        ),
    ]
